ai:
  # 唯一真相源：切换 provider 只需改这里
  default: claude

  providers:
    # Claude Code
    claude:
      cmd: "cat {prompt_file} | CLAUDECODE= claude -p --output-format text --max-budget-usd 10 --permission-mode acceptEdits --add-dir {workdir}"

    # OpenAI Codex（需要 OPENAI_API_KEY）
    codex:
      cmd: "codex exec --sandbox workspace-write --full-auto -C {workdir} - < {prompt_file}"
      cmd_agent: "codex exec --sandbox workspace-write --full-auto -C {workdir} - < {prompt_file}"

    # Kimi（Moonshot AI）
    kimi:
      cmd: "cat {prompt_file} | kimi --print --input-format text --output-format text --final-message-only -w {workdir}"

  # 讨论阶段：多 provider 左右互搏
  # "default" 占位符自动解析为 ai.default 的值
  discussion:
    providers:
      - default
      - kimi

  # 实现阶段：空值或 "default" 自动使用 ai.default
  implementation:
    provider: default

workflow:
  max_discussion_rounds: 5
  discuss_timeout_minutes: 20
  visible_round_interval: 1
  visible_only_on_diff: true
  max_iterate_rounds: 10
  # men 工程可改动路径白名单（实现阶段）
  allowed_prefixes:
    - "lib/"
    - "test/"
    - "config/"
    - "priv/"
    - "assets/"
    - "docs/"
    - "mix.exs"
    - "mix.lock"
    - "README.md"
    - ".github/workflows/"
  implement_trigger_labels:
    - "bot:plan-final"

label_guard:
  allowlist:
    - "github-actions[bot]"
    - "niuma-bot"
    - "biantaishabi2"
  mode: "dry-run"
